server:
  port: 8082

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:

      default-filters:
        - PreserveHostHeader
        - name: RemoveRequestHeader
          args:
            name: Cookie

      routes:

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/customers/**,/api/v1/cart/**,/api/v1/vendors/**

        - id: product-service
          uri: lb://PRODUCT-INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/products/**
          filters:
            - RemoveRequestHeader=Cookie

# -----------------------------
# Custom Logstash & Environment Variables
# -----------------------------
LOGSTASH_HOST: localhost
LOGSTASH_PORT: 5000
APP_ENV: dev
